// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqxNmIdv1S4Rz1ZcOwqn_sFeRtppQ51Y',
    appId: '1:92508569127:web:f46523de982536a696d802',
    messagingSenderId: '92508569127',
    projectId: 'message-board-app-940f8',
    authDomain: 'message-board-app-940f8.firebaseapp.com',
    storageBucket: 'message-board-app-940f8.firebasestorage.app',
    measurementId: 'G-JPNT230YTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTQAvkFo1DBS7blaSoPh6cJOhmVPdgS4',
    appId: '1:92508569127:android:449f122e8fbb28ef96d802',
    messagingSenderId: '92508569127',
    projectId: 'message-board-app-940f8',
    storageBucket: 'message-board-app-940f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-4o6u4wtko0cvSq0RYlTnOUJDYG0if5Y',
    appId: '1:92508569127:ios:2c142c3d44d531f996d802',
    messagingSenderId: '92508569127',
    projectId: 'message-board-app-940f8',
    storageBucket: 'message-board-app-940f8.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-4o6u4wtko0cvSq0RYlTnOUJDYG0if5Y',
    appId: '1:92508569127:ios:2c142c3d44d531f996d802',
    messagingSenderId: '92508569127',
    projectId: 'message-board-app-940f8',
    storageBucket: 'message-board-app-940f8.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqxNmIdv1S4Rz1ZcOwqn_sFeRtppQ51Y',
    appId: '1:92508569127:web:e14738a629c1b61496d802',
    messagingSenderId: '92508569127',
    projectId: 'message-board-app-940f8',
    authDomain: 'message-board-app-940f8.firebaseapp.com',
    storageBucket: 'message-board-app-940f8.firebasestorage.app',
    measurementId: 'G-R6N7KKC4QM',
  );
}
